### ISSUE TITLE
Unable to join Google Groups

### ISSUE THREAD

**Issue by tram-nguyen-n** [jsrodriguezl/Book_Club#13]
Hello! 

I am looking for the Zoom link for the meeting for Advanced R but the [Google Groups](https://groups.google.com/g/cuny-data-science-book-club) says that the content is unavailable and that I may not have permission. Is this the correct group to join to receive the link? 

Thanks,
Tram

**Comment by cmirzayi** [comment]
My mistake. I adjusted the settings. You should be able to ask to join now and I'll approve you!

Thank you for letting me know!

**Comment by StephanieTuminello** [comment]
Hi,

Could I please be taken off the email list?

Thank you,
Stephanie

**Comment by cmirzayi** [comment]
@StephanieTuminello

Hi Stephanie,

You are receiving these notifications because you are watching this Github repo. Please see the instructions here on how to adjust (or remove) your watch settings: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions#configuring-your-watch-settings-for-an-individual-repository

Thanks,
Chloe

**Comment by tram-nguyen-n** [comment]
Thanks very much @cmirzayi ! Just requested access. Looking forward to joining.
